#!/usr/bin/env python3
"""Regenerate ../pr-icons.css from the Primer Octicons in this directory.

Tern plugin stylesheets can't load local image files and ignore SVG masks, but
they render SVG data URIs as background images. Colours can't come from CSS
variables inside a data URI, so each state is painted with GitHub's own pull
request colours, picked per appearance with light-dark().

Icons: https://github.com/primer/octicons (MIT, see LICENSE). Run after
replacing an SVG:  python3 icons/generate-css.py
"""
from pathlib import Path
from urllib.parse import quote

HERE = Path(__file__).resolve().parent
# (role, Octicon, light colour, dark colour): GitHub Primer pull request states.
STATES = [
    ("prDraft", "git-pull-request-draft-16.svg", "#59636e", "#9198a1"),
    ("prOpen", "git-pull-request-16.svg", "#1a7f37", "#3fb950"),
    ("prMerged", "git-merge-16.svg", "#8250df", "#ab7df8"),
    ("prClosed", "git-pull-request-closed-16.svg", "#d1242f", "#f85149"),
]


def data_uri(svg: str, colour: str) -> str:
    painted = svg.replace("<svg ", f'<svg fill="{colour}" ', 1)
    return f'url("data:image/svg+xml;utf8,{quote(painted)}")'


def main() -> None:
    rules = ["/* Generated by icons/generate-css.py from Primer Octicons (MIT). Do not edit. */"]
    for role, name, light, dark in STATES:
        svg = (HERE / name).read_text().strip()
        rules.append(
            f"[data-role='overseer.{role}'] {{\n"
            f"  /* icons/{name} */\n"
            f"  background-image: light-dark({data_uri(svg, light)}, {data_uri(svg, dark)});\n"
            "}"
        )
    (HERE.parent / "pr-icons.css").write_text("\n".join(rules) + "\n")


if __name__ == "__main__":
    main()
